#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:
env:
   greetings: "Good Morning"
   name: "Sarah"
   lastname: "E"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-errors: true
    environment: dev
    env:
      greetings: "hello Peeps"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name . $name created this file under repo ${{ GITHUB.REPOSITORY }} and its running on OS ${{ RUNNER.OS }}"
          echo Application name is ${{ vars.APP_NAME }} and password for the same is ${{ secrets.SERVER_PASSWORD }}
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }} "
          sleep 5
        env:
          name: Nur169
          greetings: "hi"
      - name: step2 for testing
        run: |
          cat /etc/os-release
          hostname
          echo "$greetings ! from $name"
          touch /tmp/nur169
          
## Name is not important in a step
      - run: uname -a

  deploy:
       runs-on: ubuntu-latest
       needs: build
       environment: prod
       env:
        lastname: "zulkiflee"
       steps: 
        - name: step1
       run: |
          echo "$greetings ! from $name $lastname. $name created this file"
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }} "
          sleep 10
      env:
          name: Nur169
     - name: step2 for testing
       run: |
          cat /etc/os-release
          sleep 10
          hostname
          echo "$greetings ! from $name"
          touch /tmp/Nur169
