#My First Workflow

name: workflow1
on: 
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: |
          echo "good morning"
          sleep 30
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 30
## Name is not important in a step
      - run: uname -a
